### PR TITLE
Fix party stance text for single member parties

### LINKED ISSUE #1019: Wording when a party only has a single MP
As noted via a tweet:

> Douglas Carswell consistently votes the same way as "Other UKIP MPs" 

As he's the only one, we should probably drop this line if possible.

### PR DESCRIPTION
**Pull request by struan**
Add a getCurrentMemberCount method to party class and use that to check
if a party has only one member, and if so do not print a differs
from/votes the same as bit.

Fixes #1019

### CODE REVIEW

File: www/includes/easyparliament/templates/html/mp/profile.php [hunk 1]
```diff
@@ -74,13 +74,13 @@
 
                     </div>
                     <?php } ?>
-                <?php } else if (count($policyPositions->positions) > 0 || count($sorted_diffs) > 0): ?>
+                <?php } else if ($party_member_count > 0 && (count($policyPositions->positions) > 0 || count($sorted_diffs) > 0) ): ?>
```
Comment (dracos) [inline www/includes/easyparliament/templates/html/mp/profile.php]: Is it possible for this to be 0 if it was the member's own party that was used for the count?

**Comment by dracos** [comment]
:+1: with query about whether a new check is needed.

File: www/includes/easyparliament/templates/html/mp/profile.php (hunk 1 above)
Comment (struan) [inline www/includes/easyparliament/templates/html/mp/profile.php]: Good point :)
